# Generated by Django 2.2.7 on 2019-12-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('isbn', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='isbn')),
                ('bookName', models.CharField(max_length=100, verbose_name='bookName')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('press', models.CharField(max_length=100, verbose_name='press')),
                ('category_id', models.IntegerField(default=0, verbose_name='category_id')),
                ('book_number', models.IntegerField(default=0, verbose_name='book_number')),
                ('lend_number', models.IntegerField(default=0, verbose_name='lend_number')),
            ],
            options={
                'db_table': 'book_info',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('disable', models.BooleanField(verbose_name='disable')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
