# Generated by Django 2.2.7 on 2019-12-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191208_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='isbn'),
        ),
        migrations.AlterField(
            model_name='bookstatus',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='isbn'),
        ),
    ]
