# Generated by Django 2.2.7 on 2019-12-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='u_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
