# Generated by Django 2.2.7 on 2019-12-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191211_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='u_name',
            new_name='u_id',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
