# Generated by Django 2.2.7 on 2019-12-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20191211_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='u_ticket',
        ),
    ]
